name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ClamAV
        run: |
          sudo apt-get update
          sudo apt-get install -y clamav clamav-daemon
          sudo freshclam || echo "Failed to update ClamAV database"

      - name: Ensure ClamAV services are stopped
        run: |
          sudo systemctl stop clamav-freshclam || true
          sudo systemctl stop clamav-daemon || true
          sudo rm -f /var/log/clamav/freshclam.log.lock

      - name: Run ClamAV scan
        run: |
          echo "Starting ClamAV scan..."
          clamscan -r --scan-archive=yes --log=/tmp/scan.log -i . || echo "ClamAV scan completed with issues"
          if [ -f /tmp/scan.log ]; then
            cat /tmp/scan.log
          else
            echo "No scan log file found"
          fi

      - name: Upload ClamAV scan results
        uses: actions/upload-artifact@v3
        with:
          name: clamav-scan-results
          path: /tmp/scan.log

      - name: Notify if scan found issues
        if: ${{ failure() }}
        run: echo "ClamAV scan found issues. Check the logs for details."
